### PR TITLE
JavaScript bindings

### LINKED ISSUE #3: Integrate fontkit.js for WebGL
Currently, the WebGL strategy for this library does not work. We should integrate [`fontkit`](https://github.com/foliojs/fontkit) (which has an API surface very similiar, since it inspired this API surface) -for Web/JSOO compilation

### PR DESCRIPTION
**Pull request by jchavarri**
Fixes #3.

Getting started with the JS bindings (couldn't wait until the weekend 😄 ).

Some notes / findings:
- The approach of writing the bindings in JavaScript will be tricky. For example, we have to write manually the compiled representation of variants or records, which is prone to errors (happens often) and will break if at some point that representation changes (very unlikely). Not a big deal in any case.
- I've got to a point where there bindings seem to be loading fine, and I get an error downstream:
```
TypeError: Argument 6 is not valid for any of the 6-argument overloads of WebGLRenderingContext.texImage2D.
caml_glTexImage2D
file:///Users/javi/Development/github/revery/_build/default/examples/Bin.bc.js:1192:7
```

I _think_ this is due to the expected `Image` representation to be something else than a string. I have been looking at the implementation of `Glyph` in the [fontkit repo](https://github.com/foliojs/fontkit/blob/master/src/glyph/Glyph.js). It seems we'll need to convert from that object to a data type that WebGL can understand?

Will continue exploring on Friday...

### CODE REVIEW

**Comment by bryphe** [comment]
Looks like I was unfortunately mistaken here: 
> I believe that if we set the URL to a data URL it will load synchronously

I think there are two options - if __`fontkit.js` supports synchronous rendering__, we could switch to a synchronous strategy (use a canvas, or something - or just go right to integrating `fontkit.js`). If the __only option is asynchronous rendering__ - we could change the `fk_load_glyph` API to something async (like return an `Lwt` promise), and continue the image rendering strategy for this part.

The async strategy makes the API a bit more awkward, but we actually handle this already for Images in Revery:
```
      /* Create an initial texture container */
      let texture = glCreateTexture();
      glBindTexture(GL_TEXTURE_2D, texture);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
      glTexImage2D(GL_TEXTURE_2D, initialImage);

      let imageLoadPromise = Image.load(imagePath);

      let success = img => {
        glBindTexture(GL_TEXTURE_2D, texture);
        glTexImage2D(GL_TEXTURE_2D, img);
        Lwt.return();
      };

      let _ = Lwt.bind(imageLoadPromise, success);
      Hashtbl.add(_cache, imagePath, texture);
      texture;
```

So not a big deal if we have to switch to an async route!

One other thing I found - I tested the PR and it turns out we need an extra array entry at the beginning of this array:
```
  return createSuccessValue([
   /* extra val */ 0, // JSOO needs this for raw arrays coming from JS
    /* width */ face[0],
    /* height */ face[0],
    /* bearingX */ 0,
    /* bearingY */ 0,
    /* advance */ 0,
    /* image */ img,
  ]);
```

Otherwise, I was still getting an error that it was unable to load the image. There might be a helper function for this in JSOO somewhere that does this for us.

**Comment by jchavarri** [comment]
Thanks a lot for all that feedback @bryphe !

I had managed to get the white squares running by adding precisely the two changes you mentioned 😄 I think you were right originally!! Loading an image with base64 strings works synchronously 🎉  (side not: that actually [seems to be](https://stackoverflow.com/a/19973880) the only way to load an image synchronously).

Last changes are pushed to this branch.

white-squares

Some notes:
- In Chrome, it shows a warning when loading because it can't find the image, but it is the _logo_ image, not the ones from the text. If the `<Logo/>` element is removed, the `WebGL: INVALID_VALUE: texImage2D: no image` error goes away. I haven't figured out why it can't find that image yet.
- There is a `TypeError: runtime.unix_sleep is not a function` that happens at the end of the animation of the logo, I think. Not sure if jsoo doesn't have support for it?
- I had some issues in the macOS retina resolution, I had to divide the framebufferWidth and frameBufferHeight by 2 in revery `src/Core/Window` to make it look ok. I can open an issue upstream if this is not being tracked.

---

I am thinking on continue the work here, and go straight to the integration with fontkit in this PR. I'm figuring out the bundling of fontkit at the moment, and how to make it work fine with jsoo. I ran into this issue: https://github.com/ocsigen/js_of_ocaml/issues/722 because of reserved words like `default` being used as object properties in fontkit code. So I will have to point jsoo to the master branch of the github repo to see if the latest changes fix it.

re: the sync/async strategy, I think I'm going to try first to use the [canvas-based approach](https://github.com/foliojs/fontkit/blob/29751ed8eb7f1748da67fc71a0c1ac4f5322bc15/src/glyph/Glyph.js#L200) of fontkit, and depending on the issues we find, evaluate if the API has to change? I think we can do all this synchronously.

Curious to know your thoughts!

**Comment by bryphe** [comment]
> I had managed to get the white squares running by adding precisely the two changes you mentioned 😄 I think you were right originally!! Loading an image with base64 strings works synchronously 🎉 (side not: that actually seems to be the only way to load an image synchronously).

Nice! You can actually see it's rendering the 'text' - the middle bar that fades in is the smallest since it is just the word 'to'. Very cool! (And no spacing between letters, of course, because there is no advance set). Part 1 is accomplished! 🎉 

> In Chrome, it shows a warning when loading because it can't find the image, but it is the logo image, not the ones from the text. If the <Logo/> element is removed, the WebGL: INVALID_VALUE: texImage2D: no image error goes away. I haven't figured out why it can't find that image yet.

Ah, good catch. I'll take a look at this - it might be a consequence of the way we load the image (since the image loading is async, we create a texture with an empty image first, and then set it again once its loaded).

> There is a TypeError: runtime.unix_sleep is not a function that happens at the end of the animation of the logo, I think. Not sure if jsoo doesn't have support for it?

I just hit this the other day too, testing - I fixed it in this PR: https://github.com/bryphe/revery/pull/89 (`sleep` at least in the context of `Unix.sleep` doesn't make sense in JS)

> I had some issues in the macOS retina resolution, I had to divide the framebufferWidth and frameBufferHeight by 2 in revery src/Core/Window to make it look ok. I can open an issue upstream if this is not being tracked.

Yes, this is a pain point at the moment. I would really like for the developer to not need to worry about the pixel density (unless they want to). I put a first round of fixes here: https://github.com/bryphe/revery/pull/95

The idea is - to the app developer, if I say I want a window at 800 pixels, I should be able to draw my UI at 800 pixels - I shouldn't need to know that the actual underlying framebuffer is 1600 pixels - so we take care of the scaling under the hood. Important for the app to look consistent across platforms!

Unfortunately, though, I don't have a high-dpi device to test on at the moment - so it'd be great to get your feedback on the fix and see how it works. Even with that fix, there might be quirks in terms of how it works in JS vs a native window - so I anticipate we might need additional fixes to fully smooth out this scenario.

So it'd be worth pulling in the latest `master` from `revery` to see how it works!

> I am thinking on continue the work here, and go straight to the integration with fontkit in this PR. I'm figuring out the bundling of fontkit at the moment, and how to make it work fine with jsoo.

Sounds great to me! 😍 

> I ran into this issue: ocsigen/js_of_ocaml#722 because of reserved words like default being used as object properties in fontkit code. So I will have to point jsoo to the master branch of the github repo to see if the latest changes fix it.

Seems reasonable, we might as well pick up the fix as opposed to trying to make a workaround - glad you found the issue and that it was already fixed.

> re: the sync/async strategy, I think I'm going to try first to use the canvas-based approach of fontkit, and depending on the issues we find, evaluate if the API has to change? I think we can do all this synchronously.

That's perfect! If we can use that synchronous canvas strategy, it'll be easy to plug-in without needing to change the API surface.

Thanks for all the work on this, @jchavarri - awesome progress!

**Comment by jchavarri** [comment]
Hey @bryphe!

I managed to make jsoo work with the compiled version of `fontkit`. I included a `package.json` in `src`. The compiled version of the lib can be compiled with `yarn bundle`.

Another important thing is that `revery` needs to point to the GitHub version of jsoo, so these two lines need to be added to `resolutions`:

```diff
   "resolutions": {
+    "@opam/js_of_ocaml": "github:ocsigen/js_of_ocaml:js_of_ocaml.opam#db257ce",
+    "@opam/js_of_ocaml-compiler": "github:ocsigen/js_of_ocaml:js_of_ocaml-compiler.opam#db257ce",
   },
```

If not, the compilation will fail because fontkit includes reserved words like `default` as properties of objects (jsoo issue [722](https://github.com/ocsigen/js_of_ocaml/issues/722) mentioned above).

Once I managed to make a bundle with Fontkit, I realized the first API, `caml_fk_new_face`, can't be really implemented synchronously in the web. Fontkit has `fontkit.open` and `fontkit.openSync`,  but both are only for Node. They fail in the browser because `fs` is not defined. For the browser, I believe one can only use `fontkit.create`, which needs a buffer as first param.

So, the font needs to be fetched. Even if the font is fetched synchronously with `XMLHttpRequest`, one has to convert the result to a buffer, which is also an async operation (see [`blob-to-buffer`](https://github.com/feross/blob-to-buffer/blob/master/index.js), which is used by the fontkit-demo).

I wonder what you think the best approach would be. I was thinking to change the API of `Fontkit.fk_new_face` to return a [`repromise`](https://aantron.github.io/repromise/) `t` value. I'm not sure if Repromise works with jsoo though. We would be better with Lwt I guess? (i have no experience with it).

This change to asynchronicity would impose some burden on the native side though, which is not needed right now, but I'm not sure what other way there is?

**Comment by jchavarri** [comment]
I’ve done some research. There is an implementation of Lwt to/from Js promises in https://github.com/tbrk/jsoo-viz/blob/master/lwt_promise.ml

Also, there is a PR [in the jsoo repo](https://github.com/ocsigen/js_of_ocaml/pull/609) with very interesting and recent feedback on a potential addition of jsoo as platform supported in Repromise.

I think I will continue exploring a similar approach than `jsoo-viz` for now.

**Comment by bryphe** [comment]
Hey @jchavarri !

> I managed to make jsoo work with the compiled version of fontkit. I included a package.json in src. The compiled version of the lib can be compiled with yarn bundle.

That's awesome 😍 

> Another important thing is that revery needs to point to the GitHub version of jsoo, so these two lines need to be added to resolutions:

Good to know - happy to add those to revery to get it working. We can remove them with the next version of JSOO 👍 

> Once I managed to make a bundle with Fontkit, I realized the first API, caml_fk_new_face, can't be really implemented synchronously in the web. Fontkit has fontkit.open and fontkit.openSync, but both are only for Node. They fail in the browser because fs is not defined. For the browser, I believe one can only use fontkit.create, which needs a buffer as first param.

Ah bummer - I was worried this might be the case. But good to know!

> I wonder what you think the best approach would be. I was thinking to change the API of Fontkit.fk_new_face to return a repromise t value. I'm not sure if Repromise works with jsoo though. We would be better with Lwt I guess? (i have no experience with it).

Yes, sounds like we'll have to change this API to some sort of promise. When I checked `Repromise` last - it didn't have native support which was unfortunately a blocker (I like the idea of `repromise` a lot, though - would like to switch to it when available). So I used `Lwt` in the Image case:

```

**Comment by jchavarri** [comment]
Thanks a ton for all those insights @bryphe! The examples from `reason-glfw` helped me a lot to figure out the way to implement these bindings on the respective C++ and JS sides.

I got the `fk_new_face` API migrated to the new promise-based model. I had to include `Buffer` to the dependencies via this "pseudo-package.json" we're calling `fontkit-lib.js` 😄 I pushed all the latest changes.

To test these changes, I started changing `revery` API to make it compile, but I ran into this issue where I have to update [`FontCache.load`](https://github.com/jchavarri/revery/blob/09f24fdc3f7fb6bef9839d26040de0818598718a/src/UI/FontCache.re#L11) to return the new `Lwt.t(fk_face)` value, instead of just `fk_face`. However, this change cascades into also changing [`getMeasureFunction`](https://github.com/jchavarri/revery/blob/09f24fdc3f7fb6bef9839d26040de0818598718a/src/UI/TextNode.re#L119) and [`draw`](https://github.com/jchavarri/revery/blob/09f24fdc3f7fb6bef9839d26040de0818598718a/src/UI/TextNode.re#L36), which then cascade to more callers.

Are we willing to promisify all these APIs upstream? Would there be any consequences on the consumers? I'm especially concerned about this call to [`getMeasureFunction`](https://github.com/jchavarri/revery/blob/09f24fdc3f7fb6bef9839d26040de0818598718a/src/UI/Node.re#L74) which would become async after these changes 🤔 

If all's good, I can apply the changes locally and at the end submit a separate PR upstream in revery, but wanted to be sure if we're ok with this approach.

What do you think?

**Comment by bryphe** [comment]
> I got the fk_new_face API migrated to the new promise-based model. I had to include Buffer to the dependencies via this "pseudo-package.json" we're calling fontkit-lib.js 😄 I pushed all the latest changes.

Wow, this is awesome! Thanks for figuring out the build story for that 👍 

> To test these changes, I started changing revery API to make it compile, but I ran into this issue where I have to update FontCache.load to return the new Lwt.t(fk_face) value, instead of just fk_face. However, this change cascades into also changing getMeasureFunction and draw, which then cascade to more callers.

Ah ya... that's rough!

> Are we willing to promisify all these APIs upstream? Would there be any consequences on the consumers? I'm especially concerned about this call to getMeasureFunction which would become async after these changes 🤔

Yes, this is valid concern - it's problematic for the `getMeasureFunction`. What I'm thinking is that - from the perspective of the node - we could keep it 'synchronous'.  However, our `FontCache` could expose an event - `onFontLoaded` - and when we receive that event, we'll re-render the UI.

This means, internally, the `FontCache` would handle the asynchronicity of the new API. The flow would be:
1) A `TextNode` is rendered and tries to load a font face
2) Loading is kicked off asynchronously - we hand off a 'dummy' transparent font. The measurements would be all zeros.
3) Once the font is loaded - we'll re-render the UI. 
4) Upon re-render, the `TextNode` will ask `FontCache` again for the font - this time, it will actually get the real thing (and proper measurements).

I think this is pretty reasonable - it means the UI can continue running while we're waiting for the font to load. In fact I believe web pages load this way (ie, sometimes fonts snap-in and affect layout once they've been downloaded). This approach hides the 'asynchronicity' of the new API from the nodes, and only the `FontCache` and the UI has to care about that - so it keeps things relatively simple.

It's similiar to how we handle the image loading right (we hand off an empty texture while we're waiting for it to load, and then populate it once the image is actually loaded. Native is sync, but JS is async).

> If all's good, I can apply the changes locally and at the end submit a separate PR upstream in revery, but wanted to be sure if we're ok with this approach.

This sounds good! No matter what - it seems like it needs to be asynchronous here, so we'll find a way to deal with it on the Revery side.

Does that sound good to you @jchavarri ? 

cc @cryza who has done a lot of work with font / text rendering too.

**Comment by jchavarri** [comment]
> Does that sound good to you @jchavarri ?

Sounds great @bryphe ! I will play with the idea of exposing an event handler from `FontCache`. I thought about the opposite approach as well: passing the `TextNode` `render` function (or a wrapper that calls it) from `TextNode` to `FontCache`'s `load` function:

```reason
/* In FontCache.re */
let load = (fontName: string, size: int, onFontLoad: Fontkit.fk_face => unit) =>
...
```

Then from `TextNode`:
```reason
let font = FontCache.load(style.fontFamily, style.fontSize, _this#drawWithFont);
...
pub! drawWithFont = (font: fk_face, pass: renderPass, parentContext: NodeDrawContext.t) ...
```

Or something in that vein. Not sure if that approach makes sense...

Another thought is that we might set up a secondary cache for fonts being loaded, so we don't try to load the same font twice. Although that seems like a later enhancement.

In any case, I think there is enough context to move forward with this PR, I think we're quite close! ✨

**Comment by bryphe** [comment]
@jchavarri - awesome!

> I thought about the opposite approach as well: passing the TextNode render function (or a wrapper that calls it) from TextNode to FontCache's load function:

Unfortunately the architecture doesn't support this strategy at the moment (there's no incremental rendering). At this point - it's almost like a game engine, it always renders the entire UI scene. The top-level of our render pass is here: https://github.com/bryphe/revery/blob/a6f795bcbc7ba741cc7df3b6f775c60f32e63a5c/src/UI/Revery_UI.re#L98

And there's some boiler plate stuff we have to do prior to drawing (setting some GL settings). In particular, the alpha blending isn't something that's idempotent - each pass would be 'additive'. So the TL;DR is that the architecture doesn't support just rendering the `TextNode` at the moment.

It's actually really fast to do this with the GPU! But down the road we still will likely do some compositing  so that we can render sections /layers without re-rendering everything.

> Another thought is that we might set up a secondary cache for fonts being loaded, so we don't try to load the same font twice. Although that seems like a later enhancement.

Ah yes, makes sense - it would be great to handle that case!

> In any case, I think there is enough context to move forward with this PR, I think we're quite close! ✨

Definitely @jchavarri ! Thanks for all the work on it. Really excited about the potential this opens up 👍

**Comment by jchavarri** [comment]
Thanks for all the advice @bryphe ! I ended up creating an event as you proposed. I haven't created a PR in `revery` yet, but here's the exact place [where it's dispatched](https://github.com/bryphe/revery/compare/master...jchavarri:fontkit-js-support?expand=1#diff-eb66ba187af54886a62ef7dbf313b01bR27) and [here's the subscription](https://github.com/bryphe/revery/compare/master...jchavarri:fontkit-js-support?expand=1#diff-640a4a3481afc50c59eb146e8ded7331R126). Is this in the direction you had in mind? I will create the PR for that branch as soon as this one gets to a reviewable stage.

----

Some progress... 🎉 

fontkit-js

Things that remain:
- [ ] Figure out how to read metrics from glyphs: `width`, `height`, `bearingX`, `bearingY`. Haven't been able to find the way yet.
- [ ] Fix spacing between letters, prob relating with the above
- [ ] Fix letters not showing entirely, prob relating with the above as well
- [ ] Remove that strange grayed squares that appears behind
- [ ] Fix tests
- [ ] Fix native bindings: after adding `dummyFont` they break as this function as the moment is just returning a number 😅 I've tried to copy parts of `caml_fk_new_face` but I have to dig a bit more.

Almost there!

**Comment by jchavarri** [comment]
I've been trying to solve the issues with the squares that appear over the text, but with no luck. It seems that _something_ is adding them as part of the rendering process, but I can't figure out what it is.

These squares start as gray and progressively fade out to black. Ultimately, they are rendered over the text so hide a large part of it. Here's an image during the animation process:

image

And at the end:

image

(I added some offset to make more clear how they overlay)

I have tried a bunch of things like clearing the canvas, setting background colors, and also looking at the `texImage2d` which is ultimately [used in `FontRenderer`](https://github.com/jchavarri/revery/blob/49a399dad9f37b2017d842828b0607f4aecac511/src/UI/FontRenderer.re#L29). I am wondering if it has to do with the way `reason-glfw` is passing `channels` to the native `glTexImage2d` call [here](https://github.com/bryphe/reason-glfw/blob/1049d5f0e9977e1143b2ebc62307ae0ea5a083ae/src/gl_wrapper.cpp#L452-L465).

@bryphe Do you have any ideas on why this could be happening? My next step would probably be to try isolate the issue in a simpler example with just `reason-glfw`.  🤔

**Comment by jchavarri** [comment]
Found something :) If this line gets commented: [`TextNode`](https://github.com/bryphe/revery/blob/49a399dad9f37b2017d842828b0607f4aecac511/src/UI/TextNode.re#L22) then the gray squares disappear.

**Comment by bryphe** [comment]
Hey @jchavarri ! Sorry that I missed your question earlier. Thanks for the detailed checklist of remaining items! 

> Found something :) If this line gets commented in TextNode then the gray squares disappear.

Ah yes - I suspect that it was drawing a 'background' to the text.  We were _always_ drawing a background previously - but I made a recent fix in https://github.com/bryphe/revery/pull/112 that doesn't draw if the background is transparent (might address this without needing to comment out the `_super#draw`).  The `_super#draw` calls into the `ViewNode`'s `draw` is responsible for drawing the background (and later, some other common styling stuff will be there - borders, box-shadow, etc). 

It's curious though that the boxes aren't aligned with the text - I'd expect the boxes to be behind the text, and not above / clipping the text. It'd be interested to set the `~background=Colors.red` and compare the native / WebGL output. It might simply be that the glyph metrics aren't taken into account yet. The color is also strange - I'd expect it to be black and not gray. 🤔 That's a separate issue though.

>  Figure out how to read metrics from glyphs: width, height, bearingX, bearingY. Haven't been able to find the way yet.
>  Fix spacing between letters, prob relating with the above

Yes, I suspect these are related. On the native side - the `advance` property controls this. But I'm not sure what the `fontkit.js` equivalent is. 

It looks like in the `fontkit-demo` project there's an example of getting these metrics from the glyphs: 
https://github.com/devongovett/fontkit-demo/blob/138eabc280540016e971a970cd4650ce377f0dcb/src/PreviewCanvas.js#L36

```
    run.glyphs.forEach((glyph, index) => {
      let pos = run.positions[index];
      ctx.save();
      ctx.translate((x + pos.xOffset) * scale, (y + pos.yOffset) * scale);
      ctx.beginPath();
      glyph.render(ctx, fontSize);
      ctx.restore();

      x += pos.xAdvance;
      y += pos.yAdvance;
    });
```

Perhaps that example will be helpful here?

>  Figure out a way to memoize / reuse canvas elements between renders to avoid garbage collection pressure

Thanks for thinking about this! This actually might be related to a performance issue I saw on the native side too: https://github.com/bryphe/revery/issues/115 - our bottleneck today is the calls to `hb_shape`. I was considering adding caching / memoization around our `fk_shape` call in revery - I wonder if that hits the same codepath?

>  Fix native bindings: after adding dummyFont they break as this function as the moment is just returning a number 😅 I've tried to copy parts of caml_fk_new_face but I have to dig a bit more.

Haha, makes sense 👍  Let me know if I can help with any blockers.

 Awesome progress @jchavarri ! 🔥 🔥

**Comment by jchavarri** [comment]
@bryphe thanks for https://github.com/bryphe/revery/pull/112! It fixed the issue with the black background! 🎉 

I have fixed the cpp bindings to work with the async API. I had to use some [hacks](https://github.com/bryphe/reason-fontkit/pull/6/files#diff-d284dc4da9f1f4d3da457d821d7889bcR231) in order to identify which fonts are "dummy", but happy to make this code cleaner. My C++ mojo has been gone for maaaaany years I'm afraid 😄 

There are a few remaining improvements to do on the fonts handling, but maybe they could be tackled in a separate PR? Due to retina screens breaking revery rendering in the browser quite badly, the font issues are hard to debug, as I'm never sure I'm looking at the right spaces. They might need to get fixed upstream in revery, and unfortunately I don't have any regular density display machine at hand.

The last obstacle is the tests not passing. I get this error:

```
2018-12-19T00:56:32.7681290Z     cmake
2018-12-19T00:56:32.7682000Z     libfreetype.a
2018-12-19T00:56:32.7682440Z     pkgconfig
2018-12-19T00:56:32.7683460Z     ld: library not found for -lpng
2018-12-19T00:56:32.7684440Z     clang: error: linker command failed with exit code 1 (use -v to see invocation)
2018-12-19T00:56:32.7684930Z     ./esy/test.sh: line 21: ./test: No such file or directory
2018-12-19T00:56:32.7685920Z     error: command failed: './esy/test.sh' (exited with 127)
2018-12-19T00:56:32.7686850Z     esy-build-package: exiting with errors above...
```

Do you know where this problem could be originating? Seems a problem with the esy installation itself?

As an aside, I created https://github.com/bryphe/revery/pull/116 upstream in revery, it's the companion PR of this one.

**Comment by jchavarri** [comment]
Thanks a lot for your comments and hints @bryphe !

> It'd be interested to set the ~background=Colors.red and compare the native / WebGL output.

This is native:

image

This is browser, with a few tweaks to fix for retina rendering (I have to divide framebuffer lengths between 2 [in `Window.re`](https://github.com/jchavarri/revery/blob/4b293d0d327c7126479142e6c7f4623f55ec1dca/src/Core/Window.re#L154-L155)):

image

As you can see, the text is not rendered inside the box. The reason is that if I don't make this call to `ctx.translate` [here](https://github.com/bryphe/reason-fontkit/pull/6/files#diff-7d8da91261a9949e5c1334f08e99d91aR80), which puts the text inside the red box, then the text gets hidden behind the red box. I'm not sure why.

> Yes, I suspect these are related. On the native side - the advance property controls this. But I'm not sure what the fontkit.js equivalent is.

> It looks like in the fontkit-demo project there's an example of getting these metrics from the glyphs:
https://github.com/devongovett/fontkit-demo/blob/138eabc280540016e971a970cd4650ce377f0dcb/src/PreviewCanvas.js#L36

Thanks for this hints. After further look, I _think_ I'm setting the `advance` value ok, and the problem might be related to pixel density issues... I'd need to be able to test this in regular, non-retina screens to be sure.

**Comment by Cryza** [comment]
Hey guys! Sorry for chiming in so late.

I agree that we should ideally keep everything synchronous if possible. Going async would leak into the complete API and make everything harder to use.

The dummy font approach sounds like a very reasonable thing to do. Would it even be possible to bundle an actual default font with our application so that we don't have to serve an empty font but rather fall back to that actual bundled font so that we can draw something?

> They fail in the browser because fs is not defined.

Taking a more general perspective here, do you think we will need to find a way to replace `fs` in the browser long-term? Maybe it would be sensible to investigate into that direction as well if it enables us to synchronously access font files. I don't know if browsers allow this anyway, so I'm just asking into the blue here.

**Comment by jchavarri** [comment]
Hey @Cryza ! Thanks for your feedback 🙂 

> I agree that we should ideally keep everything synchronous if possible. Going async would leak into the complete API and make everything harder to use.

The hybrid "async API but returning synchronously a dummy value" is already in place, but with a dummy font, as you mentioned.

> Would it even be possible to bundle an actual default font with our application so that we don't have to serve an empty font but rather fall back to that actual bundled font so that we can draw something?

Probably, but that would force users to pay that default font tax on their bundles no? It would be interesting to know if there's a way to preprocess the font files and inline the data in the code, with a PPX maybe 🤔  It could be an interesting exploration for a future iteration :)

> Taking a more general perspective here, do you think we will need to find a way to replace fs in the browser long-term?

For now, the workaround using the [`Buffer` polyfill](https://github.com/bryphe/reason-fontkit/pull/6/files#diff-7d8da91261a9949e5c1334f08e99d91aR29) like it's being done in the fontkit-demo seems to work. Do you think we should include `fs` as well?

----

As an update of the current status, I've kept investigating the font metrics in fontkit and trying to make them the same as the C++ version. It's really tricky because while the C++ version provides directly a bitmap / image (which makes things _much_ easier) fontkit only gives a way to render the glyph in a canvas. This makes everything more complex because all the metrics lose definition while rounding to integers, etc. I wonder if there's a way to just get an image with fontkit instead of having to calculate these values manually?

I managed to improve the rendered text a bit by inspecting the bearing, size and advance values from the native version and trying to derive the calculations needed in JS, but it still needs some refinement:

image

**Comment by bryphe** [comment]
Wow, incredible progress! 😍  It's looking great!

Glad you figured out the metrics / positioning issues (that 64-unit advance is confusing!)

> Avoid passing the internal bbox width and height of the glyph, and instead render each glyph on a canvas of size fontSize x fontSize. Doing otherwise, like using bbox measurements, leads to characters being cropped. The downside of using the font size is that we're using more memory that what we actually need, but I think this approach might be enough for now...

This seems reasonable to me - we can always optimize further later. I don't believe we optimize this on the native side at the moment either. Might impact the texture-atlas work @Cryza is doing, though!

> @bryphe The last thing remaining would be the tests, I think. Unfortunately I can't figure out what the error is about. Do you have any hints on what could be causing the build to fail? Could it be the package.json added to include the fontkit-lib JS lib?

This is purely on the native side - it needs the `libpng` library to build the native portion. I think this is actually a bug with the build script... we're missing that dependency. I'm actually not sure how it passed before! I created #77 to fix this - sorry about that.

@Cryza - regarding this: 
> Taking a more general perspective here, do you think we will need to find a way to replace fs in the browser long-term? Maybe it would be sensible to investigate into that direction as well if it enables us to synchronously access font files. I don't know if browsers allow file system access in any way, so I'm just asking into the blue here.

Yeah, actually I was wondering about this too. I experimented with an abstracted API here: https://github.com/bryphe/revery/blob/master/src/Core/File.re (it used an `XMLHttpRequest` in JS, and `fopen`/`fread` in native - the idea was to have a consistent way to get at the data in a file). It's not really used right now, but I am interested in a good abstraction to solve this problem.

As a side note - I'm actually working on a node-like cross-platform abstraction layer here - https://github.com/bryphe/rench - that might be a good place for us to think about an `fs` like abstraction that works everywhere.

**Comment by Cryza** [comment]
This looks like really great progress! Awesome!

> Need to multiply advance by 64, after also multiplying it by the font scale ((1 / font.unitsPerEm) * font.size)

The 64 is probably related to the fixed-point representation that FreeType uses for some of its measures. They represent some numbers in multiples of `1/64` of a pixel for the `26.6` format (others even use `16.16`, i.e. multiples of `1/35536`).

> Avoid passing the internal bbox width and height of the glyph, and instead render each glyph on a canvas of size fontSize x fontSize.

I checked out some of the text rendering code in chromium before and found that they use a line height of 1.2 by default also in canvases. They distribute the added 20% of vertical space above and below the glyph, which might end up in the glyph bitmap not actually starting at the top end of the canvas. I'm not 100% sure if I remember this correctly though.

> Yeah, actually I was wondering about this too. I experimented with an abstracted API here: bryphe/revery:src/Core/File.re@master (it used an XMLHttpRequest in JS, and fopen/fread in native - the idea was to have a consistent way to get at the data in a file)

I thought about this some more and I think I would like to remove the concern of providing the font data itself from the `reason-fontkit` library in general. If we want to be platform-agnostic, we should not make any assumptions about the means of file access that we have at our disposal. I think it would be a better idea to leave that concern up to the consumers since only they know how to acquire the font file.
I get that the JS `fontkit` library made that decision because they were primarily targeting node environments but maybe it would make sense to get rid of that burden here? We are much more platform-agnostic, after all.

**Comment by jchavarri** [comment]
> This seems reasonable to me - we can always optimize further later. I don't believe we optimize this on the native side at the moment either. Might impact the texture-atlas work @Cryza is doing, though!

@bryphe Oooh this sounds really promising! One of the things I'd like to fix at some point is the fact that we're creating one canvas element per glyph at the moment, but I'm pretty sure that there is a way to reuse the same canvas and use the width, height and bearings to kind of pick the subregion of that canvas that contains the glyph.

> This is purely on the native side - it needs the libpng library to build the native portion. I think this is actually a bug with the build script... we're missing that dependency. I'm actually not sure how it passed before! I created #77 to fix this - sorry about that.

Thanks @bryphe ! I was scratching my head about this 😄 

> I thought about this some more and I think I would like to remove the concern of providing the font data itself from the reason-fontkit library in general.

@Cryza I like this idea! It makes a ton of sense.

I was wondering how this would look like from the type system perspective. Would the `File` generic interface use a low level type like `Bigarray` to represent the data, like in the [exploration](https://github.com/bryphe/revery/blob/master/src/Core/File.re#L2) @bryphe shared?

**Comment by bryphe** [comment]
Sorry about the delay @jchavarri , I fixed the builds (I disabled appveyor/travis - only building with Azure CI now - and that's unblocked)

**Comment by jchavarri** [comment]
Thanks @bryphe ! The builds seem to pass now 🎉 

This is ready, as far as I can tell. The part that I'm less confident in is the C++ file 😅  where I added a bunch of [hacks](https://github.com/jchavarri/reason-fontkit/blob/b1c5bdbba990494cd4a2a41ef4c4fce93ab96199/src/fontkit.cpp#L229-L236) to get the dummy font to work. It is working, but I'm sure there must be simpler ways to achieve the same result.

Things that could be tackled in the future could be:
- test with different font types
- reuse the canvas element between glyphs as we mentioned
- performance optimizations (maybe? not sure if it's better to leave up to the consumers the decision on how to optimize)
- the separation of concerns for files read ops, discussed above as well
- tweaks to improve positioning, rendering quality etc.

---

> I was curious about this too - at the moment, we send a string path to both freetype2 (via FT_New_Face) and harfbuzz (via get_font_ot) - are there alternative APIs that would take something else, like a binary buffer? If not, we might be stuck with paths as the common denominator between APIs.

@bryphe In the case of FT, there is an API to create a font from memory it seems: [FT_New_Memory_Face](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_New_Memory_Face).

For harfbuzz, it seems we're using `hb_blob_create` which already expects raw data, so the file opening operation that is currently happening [here](https://github.com/jchavarri/reason-fontkit/blob/b1c5bdbba990494cd4a2a41ef4c4fce93ab96199/src/fontkit.cpp#L68-L75) would be removed and placed in `rench` or the package where the low level file management handling would happen. The tricky thing would be how to make the conversation from:

host platform data types (`rench` side) -> OCaml/Reason data types -> host platform data types (`fontkit` side)

and make all that work smoothly. But sounds like there can be a promising path!

**Comment by bryphe** [comment]
@jchavarri - just tried it out. So cool!

> This is ready, as far as I can tell. The part that I'm less confident in is the C++ file 😅 where I added a bunch of hacks to get the dummy font to work. It is working, but I'm sure there must be simpler ways to achieve the same result.

Sure thing! I think there are still some things we'll have to figure out with the font-loading above (like, do we switch to a buffer/blob as opposed to a file path?) and those may impact the strategy, anyway. But this works and gets the job done 👍 

And nice find on those APIs - that does seem like a promising path (especially in combination with the discussion https://github.com/revery-ui/revery/pull/153)!

This looks great to me. I was blown away when I just loaded it up with this + the revery changes and everything just worked. Really amazing that to see it just work across web / native 💯 

Approved! Don't want to hold this up anymore - it'll make it easier to test revery in the browser too (I was always commenting out text blocks before, no need for that anymore). We can track anything remaining in separate issues to follow-up later 👍

**Comment by jchavarri** [comment]
Thanks @bryphe !! Merging this in then 🎉

**Pull request merged**
